"""상수. 출처는 control_plane.md 2.6 상수다. 값을 바꾸려면 그 절을 먼저 고친다.

MAX_CANDIDATES 와 PUNCH_DELAY_MS 는 protocol.md 가 소유하는 값의 복사다 (2.6).
"""

CONTROL_PORT = 8000
MAX_PEERS = 5
ROOM_LEASE_S = 120
HOST_REPORT_OPEN_S = 5
HOST_REPORT_FULL_S = 30
JOIN_REGISTER_GRACE_S = 90
STORAGE_GRACE_S = 86400
PUNCH_DELAY_MS = 1000
MAX_CANDIDATES = 8
MAX_BODY_BYTES = 4096
MAX_HEADER_BYTES = 2048
SERVER_READ_TIMEOUT_S = 5
CLIENT_CONNECT_TIMEOUT_S = 3
CLIENT_IO_TIMEOUT_S = 3
MAX_ROOM_ID_ATTEMPTS = 4
MAX_PEER_ID_ATTEMPTS = 4
RATE_LIMIT_BUCKET = 10
RATE_LIMIT_REFILL_PER_MIN = 10
MAX_RATE_ENTRIES = 4096
MAX_INFLIGHT = 32
MAX_REJECTING = 64
LINGER_S = 1
LINGER_MAX_BYTES = 8192

OPS = ("create_room", "join_room", "register_candidate", "get_peers", "host_report")
